image: node:12.18.3

pages:
    script:
        - npm install
        - CI=true npm run build
        - rm -Rf $CI_PROJECT_DIR/public/*
        - mv build/* $CI_PROJECT_DIR/public/
    artifacts:
        paths:
            - public

    only:
        - master
