image: node:12.18.3

cache:
    paths:
        - node_modules/

variables:
    REACT_APP_API_KEY: AIzaSyBYn18FTAPHBgMWeAWb8nGleAZbh6wGYTw
    REACT_APP_AUTH_DOMAIN: chatroomreact-4ee9b.firebaseapp.com
    REACT_APP_DATABASE_URL: https://chatroomreact-4ee9b.firebaseio.com
    REACT_APP_PROJECT_ID: chatroomreact-4ee9b
    REACT_APP_STORAGE_BUCKET: chatroomreact-4ee9b.appspot.com
    REACT_APP_MESSAGING_SENDER_ID: 813914403482
    REACT_APP_APP_ID: 1:813914403482:web:1caeaaa7d33b93321f2523

pages:
    script:
        - npm install
        - CI=true npm run build
        - rm -Rf $CI_PROJECT_DIR/public/*
        - mv build/* $CI_PROJECT_DIR/public/
    artifacts:
        paths:
            - public

    only:
        - master
