export default {
    // USERS TYPES
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    GET_CHAT_USERS: 'GET_CHAT_USERS',

    // CHAT USER TYPES
    SET_CHAT_USER: 'SET_CHAT_USER',
    SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE',
    GET_CHAT_MESSAGES: 'GET_CHAT_MESSAGES',
    GET_NEW_MESSAGES: 'GET_NEW_MESSAGES',
    RESET_CHAT_MESSAGES: 'RESET_CHAT_MESSAGES',
    ON_DELETE_MESSAGE: 'ON_DELETE_MESSAGE',
};
