export default {
    // USER TYPES
    USER_SIGN_IN: 'USER_SIGN_IN',
    USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
    USER_SIGN_OUT_SUCCESS: 'USER_SIGN_OUT_SUCCESS',

    USER_SIGN_UP: 'USER_SIGN_UP',
    USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
    USER_SIGN_UP_FAILED: 'USER_SIGN_UP_FAILED',

    USER_SIGN_OUT: 'USER_SIGN_OUT',

    GET_CURRENT_USER: 'GET_CURRENT_USER',

    // MESSAGE TYPES
    GET_NEW_MESSAGE: 'GET_NEW_MESSAGE',
};
