export default {
    // USERS TYPES
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    GET_USERS_WITH_CHATS: 'GET_USERS_WITH_CHATS',

    // CHAT USER TYPES
    SET_USERS_WITH_CHATS: 'SET_USERS_WITH_CHATS',
    SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE',
    GET_CHAT_MESSAGES: 'GET_CHAT_MESSAGES',
    GET_NEW_MESSAGES: 'GET_NEW_MESSAGES',
    RESET_CHAT_MESSAGES: 'RESET_CHAT_MESSAGES',
    ON_DELETE_MESSAGE: 'ON_DELETE_MESSAGE',
    ON_DELETE_CHAT: 'ON_DELETE_CHAT',
    GET_USER_CHATS: 'GET_USER_CHATS',
    SET_CHAT_AS_READ: 'SET_CHAT_AS_READ',
    ON_CURRENT_CHAT_USER: 'ON_CURRENT_CHAT_USER',
};
